fixtures:
    symlinks:
      freeradius: "#{source_dir}"
    forge_modules:
      concat:
        repo: "puppetlabs/concat"
        ref: "4.1.1"
      firewall:
        repo: "puppetlabs/firewall"
        ref: "1.8.1"
      logrotate:
        repo: "puppet/logrotate"
        ref: "3.2.0"
      stdlib:
        repo: "puppetlabs/stdlib"
        ref: "4.20.0"
